name: PR Tests

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 16
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        run: npm install
      - name: Patch Packages
        run: npx patch-package
      - name: ESlint
        run: npm run test:lint
      - name: Jest
        run: npm run test:code
