name: Publish

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: 16
          cache-dependency-path: "**/package-lock.json"
      - name: Install Dependencies
        run: npm install
      - name: Patch Packages
        run: npx patch-package
      - name: ESlint
        run: npm run test:lint
      - name: Jest
        run: npm run test:code
  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_REGISTRY_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Prepare
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_REGISTRY_TOKEN }}
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Version Bump
        run: npx lerna version --yes
      - name: Publish To GitHub
        run: npx lerna publish from-package --yes --ignore-scripts --registry https://npm.pkg.github.com
      - name: Publish To NPM
        run: npx lerna publish from-package --yes --ignore-scripts --registry https://registry.npmjs.org
