name: Publish

on:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore:release')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Dependencies
        run: npm ci
      - name: ESlint
        run: npm run test:lint
      - name: Jest
        run: npm run test:code
  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Prepare
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Version Bump
        run: npx lerna version --yes
      - name: Publish To GitHub
        run: npx lerna publish from-package --yes --ignore-scripts --registry https://npm.pkg.github.com
      - name: Publish To NPM
        run: npx lerna publish from-package --yes --ignore-scripts --registry https://registry.npmjs.org
