name: pull requests actions

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: 12.x
      - name: Prepare
        run: npm ci
      - name: ESlint
        run: npm run test:lint
      - name: Jest
        run: npm run test:code
