name: push actions

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore:release')"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: 12.x
      - name: Prepare
        run: npm ci
      - name: ESlint
        run: npm run test:lint
      - name: Jest
        run: npm run test:code
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: packages/
  publish:
    needs: tests
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip-publish')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: 12.x
      - uses: actions/download-artifact@v1
        with:
          name: artifacts
          path: packages/
      - name: Prepare
        run: |
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
          npm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          git fetch --depth=1 origin +refs/tags/*:refs/tags/*
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - name: Bump version
        run: npx lerna version --yes
      - name: Publish-github
        run: npx lerna publish from-package --yes --ignore-scripts --registry https://npm.pkg.github.com
      - name: Publish-npm
        run: npx lerna publish from-package --yes --ignore-scripts --registry https://registry.npmjs.org
